### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by asyrafroslanmy** [XanthanGumm/SuperSimpleMH#2]
i got this error

`[!] RPC server is up.
client connection terminated abruptly
Traceback (most recent call last):
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\utils\server.py", line 183, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\utils\server.py", line 204, in _serve_client
    conn = self.service._connect(Channel(SocketStream(sock)), config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\core\service.py", line 106, in _connect
    self.on_connect(conn)
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\map_server\MapService.py", line 10, in on_connect
    self._session = Session()
                    ^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\map_server\session\Session.py", line 30, in __init__
    settings = tomllib.load(file)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 598, in parse_value
    return parse_one_line_basic_str(src, pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 409, in parse_one_line_basic_str
    return parse_basic_str(src, pos, multiline=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 575, in parse_basic_str
    pos, parsed_escape = parse_escapes(src, pos)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 490, in parse_basic_str_escape
    return parse_hex_char(src, pos, 8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 504, in parse_hex_char
    raise suffixed_err(src, pos, "Invalid hex value")
tomllib.TOMLDecodeError: Invalid hex value (at line 2, column 13)
Exception in thread RpycSpawnThread-builtins.method-1701809296-16259176:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\utils\server.py", line 183, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\utils\server.py", line 204, in _serve_client
    conn = self.service._connect(Channel(SocketStream(sock)), config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\core\service.py", line 106, in _connect
    self.on_connect(conn)
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\map_server\MapService.py", line 10, in on_connect
    self._session = Session()
                    ^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\map_server\session\Session.py", line 30, in __init__
    settings = tomllib.load(file)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 598, in parse_value
    return parse_one_line_basic_str(src, pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 409, in parse_one_line_basic_str
    return parse_basic_str(src, pos, multiline=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 575, in parse_basic_str
    pos, parsed_escape = parse_escapes(src, pos)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 490, in parse_basic_str_escape
    return parse_hex_char(src, pos, 8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\tomllib\_parser.py", line 504, in parse_hex_char
    raise suffixed_err(src, pos, "Invalid hex value")
tomllib.TOMLDecodeError: Invalid hex value (at line 2, column 13)
Traceback (most recent call last):
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\stream.py", line 268, in read
    buf = self.sock.recv(min(self.MAX_IO_CHUNK, count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Scripts\super_simple_mh.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 22, in main
    raise e
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 20, in main
    canvas.event_loop()
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\su_core\window\__init__.py", line 227, in event_loop
    self.map_cli.set_requirements(current_seed, difficulty)
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\su_core\utils\RPYClient.py", line 32, in set_requirements
    self._conn.root.set_map_seed(seed)
    ^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\protocol.py", line 751, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\protocol.py", line 718, in sync_request
    return _async_res.value
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\async_.py", line 106, in value
    self.wait()
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\async_.py", line 51, in wait
    self._conn.serve(self._ttl)
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\protocol.py", line 438, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\channel.py", line 55, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\SuperSimpleMH (1)\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\stream.py", line 277, in read
    raise EOFError(ex)
EOFError: [WinError 10053] An established connection was aborted by the software in your host machine
Press any key to continue . . .`

**Comment by XanthanGumm** [comment]
I'll take a look into it tomorrow evening, I'm outside home.

**Comment by XanthanGumm** [comment]
Looks like rpyc-d2-map-api server is not able to decode the string in settings.toml.
Did you separate each directory in the path by double slash or maybe missing quotation marks are missing?
For instance, "C:\\Example\\d2load"

**Comment by asyrafroslanmy** [comment]
i setup the directory of path exactly as this ( path = "C:\Users\user\Downloads\game\Diablo II" ) still same error apear

**Comment by XanthanGumm** [comment]
path should be path = `"C:\\Users\\user\\Downloads\\game\\Diablo II"`
By the way, is Diablo II is the folder where game.exe is located?

**Comment by asyrafroslanmy** [comment]
by doing double slash on path at setting it working! thx so much
