### ISSUE TITLE
Still Crahsing

### ISSUE THREAD

**Issue by Dizney42** [XanthanGumm/SuperSimpleMH#4]
Mem::get_unit_table_address::INFO:: Unit table has been found at offset: 0x14d2da + (7)
Mem::get_expansion_address::INFO:: Expansion has been found at offset: 0x1532b6 + (3)
Mem::get_ui_address::INFO:: UI has been found at offset: 0x23db53 + (6)
Mem::get_minions_address::INFO:: Players minions has been found at offset: 0x207e86 + (3)
Mem::get_roster_address::INFO:: Roster has been found at offset: 0x1c7716 - (3)
Mem::get_last_hover_address::INFO:: Last hover has been found at offset: 0x17a0e4 + (3)
[!] RPC server is up.
MapManager::initialize::INFO:: [!] Initialize MapManager with seed: 0x1c9aa713, at normal difficulty
MapManager::update::INFO:: [!] Requesting area data for area: 1
MapManager::update::INFO:: [!] Requesting Act1 map levels grids
MapManager::update::INFO:: [!] Loading Act1 textures
MapManager::update::INFO:: [!] Finished to load Act1 map levels after: 5.782497200000023 seconds
MapManager::get_level_data::INFO:: [!] Caching area data for area: 1
MapManager::update::INFO:: [!] Requesting area data for area: 2
MapManager::get_level_data::INFO:: [!] Caching area data for area: 2
MapManager::update::INFO:: [!] Requesting area data for area: 8
MapManager::get_level_data::INFO:: [!] Caching area data for area: 8
MapManager::update::INFO:: [!] Player switched from Act85 at the middle of processing Act-17 maps
MapManager::update::INFO:: [!] Waiting for Act-17 maps requests to finish
MapManager::update::WARNING:: [!] Canceling the process of up scaling Act-17 maps
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Tobibelle\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Tobibelle\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Tobibelle\Desktop\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 32, in run
    raise e
  File "C:\Users\Tobibelle\Desktop\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 30, in run
    canvas.event_loop()
  File "C:\Users\Tobibelle\Desktop\SuperSimpleMH\venv\Lib\site-packages\su_core\canvas\__init__.py", line 168, in event_loop
    self._map_manager.update(area=player_area, player_pos=player.path.position)
  File "C:\Users\Tobibelle\Desktop\SuperSimpleMH\venv\Lib\site-packages\su_core\canvas\MapManager.py", line 96, in update
    progress_max_value = 2 * len(self._acts_levels[self._game_ui.last_act]) + progress_value
                                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by XanthanGumm** [comment]
fix it by installing the newest version
