### ISSUE TITLE
Unable to start SSMH using latest version

### ISSUE THREAD

**Issue by noinput** [XanthanGumm/SuperSimpleMH#5]
Hi,

I am unable to start SuperSimpleMH. I first suspected the Windows firewall but after disabling it i am still not able to get it started.

Error message attached:
```

Type 1, 2 then press ENTER:2
None
Mem::get_unit_table_address::INFO:: Unit table has been found at offset: 0x1520f1 + (7)
Mem::get_expansion_address::INFO:: Expansion has been found at offset: 0x157946 + (3)
Mem::get_ui_address::INFO:: UI has been found at offset: 0x247233 + (6)
Mem::get_minions_address::INFO:: Players minions has been found at offset: 0x2122a0 + (3)
Mem::get_roster_address::INFO:: Roster has been found at offset: 0x1cf556 - (3)
Mem::get_last_hover_address::INFO:: Last hover has been found at offset: 0x1820f4 + (3)
[!] RPC server is up.
client connection terminated abruptly
Traceback (most recent call last):
  File "C:\personal\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\utils\server.py", line 183, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "C:\personal\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\utils\server.py", line 204, in _serve_client
    conn = self.service._connect(Channel(SocketStream(sock)), config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\rpyc\core\service.py", line 106, in _connect
    self.on_connect(conn)
  File "C:\personal\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\map_server\MapService.py", line 9, in on_connect
    self._session = Session()
                    ^^^^^^^^^
  File "C:\personal\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\map_server\session\Session.py", line 37, in __init__
    if not self.d2api.initialize():
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\rpyc-d2-map-api\venv\Lib\site-packages\map_server\pyWrappers\ApiWrapper.py", line 102, in initialize
    return self._Initialize(self._path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x1D87C7F3
Exception in thread RpycSpawnThread-builtins.method-1383525432-16988744:
Process Process-2:
Traceback (most recent call last):
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\stream.py", line 268, in read
    buf = self.sock.recv(min(self.MAX_IO_CHUNK, count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 32, in run
    raise e
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 29, in run
    canvas = Canvas(shared_memory)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\su_core\canvas\__init__.py", line 104, in __init__
    self._map_manager = MapManager(self._texture_scalar)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\su_core\canvas\MapManager.py", line 25, in __init__
    self._rpyc_client: RPYClient = RPYClient()
                                   ^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\su_core\utils\RPYClient.py", line 11, in __init__
    self._async_read_map_data = rpyc.async_(self._conn.root.get_level_data)
                                            ^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\protocol.py", line 777, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\protocol.py", line 744, in sync_request
    return _async_res.value
           ^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\async_.py", line 109, in value
    self.wait()
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\async_.py", line 51, in wait
    self._conn.serve(self._ttl, waiting=self._waiting)
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\protocol.py", line 464, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
                                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\channel.py", line 55, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\SuperSimpleMH\venv\Lib\site-packages\rpyc\core\stream.py", line 277, in read
    raise EOFError(ex)
EOFError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by XanthanGumm** [comment]
The new patch broke the mh. There is a need for a fix.

**Comment by codegotv** [comment]
Are we going to get a update @XanthanGumm ?

Thanks for your hard work on this.
